openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
 
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /green:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      description: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtrenalService'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'          

        '405':
          description: Invalid input

    get:
      tags:
        - green
      summary: Find green APO

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceName'          
            
        '400':
          description: Invalid ID supplied


    
components:
  schemas:
    ServiceName:
      type: object
      properties:
        name:
          type: string
        requestURI:
          type: string
        host:
          type: string
        protocol:
          type: string
        PrivateIp:
          type: array
          items:
            type: string
    Response:
      type: object
      properties:
        externalServiceName:
          $ref: '#/components/schemas/ServiceName'
        myIP:
          type: array
          items:
            type: string
    ExtrenalService:
      type: object
      properties:
        url:
          type: string
