// Package lib provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package lib

// ExtrenalService defines model for ExtrenalService.
type ExtrenalService struct {
	Url *string `json:"url,omitempty"`
}

// Response defines model for Response.
type Response struct {
	ExternalServiceName interface{}
	MyIP                *[]string
}

// ServiceName defines model for ServiceName.
type ServiceName struct {
	PrivateIp  *[]string `json:"PrivateIp,omitempty"`
	Host       *string   `json:"host,omitempty"`
	Name       *string   `json:"name,omitempty"`
	Protocol   *string   `json:"protocol,omitempty"`
	RequestURI *string   `json:"requestURI,omitempty"`
}

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = ExtrenalService
