name: code integration
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - 'feature/**'
      - 'bug/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  unitTestExecutionAndTestcoverage:
    name: Unit test execution and test coverage
    runs-on: ubuntu-latest
    outputs:
      jobResultFileName: ${{ steps.dipalayTestResult.outputs.unitTestResultFile }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          check-latest: true
          cache: false
      - name: install go dependecies
        run: | 
              go get .
              go mod tidy
      - name: generate test coverage
        run: | 
              go test -v ./... -coverprofile=./cover.out > test.result
      - name: check test coverage
        uses: ylasmak/go-coverage-test@main
        with:
          # Configure action using config file (option 1)
          profile: cover.out
          threshold-file: 80
          threshold-package: 80
          threshold-total: 80
      - name: display test result
        id: dipalayTestResult
        if: always()
        run: |
            cat test.result > unitTestExecutionAndTestcoverage.result
            cat code_coverage.result >> unitTestExecutionAndTestcoverage.result
            cat unitTestExecutionAndTestcoverage.result
            echo 'unitTestResultFile=unitTestExecutionAndTestcoverage.result' >> "$GITHUB_OUTPUT"
      - name: Upload Test result as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ${{ steps.dipalayTestResult.outputs.unitTestResultFile }}
  codeVulnerabiltyScan:
    runs-on: ubuntu-latest
    outputs:
      jobResultFileName: ${{ steps.displaySecurityScanResult.outputs.securityScanResultFile }}
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Run install prerequiste
        run: |
            go get .
            go mod tidy
      - name: Install govulncheck
        run: |
            go install github.com/securego/gosec/v2/cmd/gosec@latest
            go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: |
            govulncheck ./... > securityScanResult.result
            gosec ./...      >> securityScanResult.result
      - name: Display security test result
        if: always()
        id: displaySecurityScanResult
        run: |
            echo 'securityScanResultFile=securityScanResult.result' >> "$GITHUB_OUTPUT"
            cat  securityScanResult.result
      - name: Upload Test result as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ${{ steps.displaySecurityScanResult.outputs.securityScanResultFile }}
  codeQualityScan:
    name: Code Linting scan
    runs-on: ubuntu-latest
    outputs:
      jobResultFileName: ${{ steps.displayCodeQualityScanResult.outputs.codeQuqlityScanResultFile }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          check-latest: true
          cache: false
      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0
      - name: run golangci-lint
        run: golangci-lint run ./...  > codeQualityScan.result
      - name: Display lint result
        if: always() 
        id: displayCodeQualityScanResult
        run: |
            echo 'codeQuqlityScanResultFile=codeQualityScan.result' >> "$GITHUB_OUTPUT"
            cat codeQualityScan.result
      - name: Upload Test result as artifact
        if:   always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ${{ steps.displayCodeQualityScanResult.outputs.codeQuqlityScanResultFile }}
  updatePullRequestWithComments:
    name: Update Pull Request With comment
    runs-on: ubuntu-latest
    needs: [ unitTestExecutionAndTestcoverage, codeVulnerabiltyScan, codeQualityScan]
    if: github.event_name == 'pull_request' && always()
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: test-result
      - name: Display structure of downloaded files
        run: |
          ls -l
          echo "------"
          ls -R
        working-directory: test-result/test-result
